### ISSUE TITLE
`textFromContent()` not handling string passed by `seoKeywords()` from ynmstudio/craft-utility

### ISSUE THREAD

**Issue by denisyilmaz** [yoannisj/craft-tailor#2]
Our utility functions `seoKeywords()` is failing when $attributes is a string, because the `textFromContent()`helper function is only accepting arrays:

```2022-12-04 12:21:21 [web.ERROR] [nystudio107\seomatic\helpers\MetaValue::parseMetaString] Error rendering `{{ craft.ynm.seo.seoKeywords(entry, 'description, title') }}` -> yoannisj\tailor\helpers\ContentHelper::textFromContent(): Argument #2 ($inAttributes) must be of type ?array, string given, called in /home/deignis-prod/webapps/deignis-web-production/releases/1670155807541/vendor/ynmstudio/craft-utils/src/services/Content.php on line 144 - {{ craft.ynm.seo.seoKeywords(entry, 'description, title') }} {"memory":85574240} 
2022-12-04 12:21:21 [web.ERROR] [TypeError] yoannisj\tailor\helpers\ContentHelper::textFromContent(): Argument #2 ($inAttributes) must be of type ?array, string given, called in /home/deignis-prod/webapps/deignis-web-production/releases/1670155807541/vendor/ynmstudio/craft-utils/src/services/Content.php on line 144 {"trace":["#0 /home/deignis-prod/webapps/deignis-web-production/releases/1670155807541/vendor/ynmstudio/craft-utils/src/services/Content.php(144): yoannisj\\tailor\\helpers\\ContentHelper::textFromContent()","#1 /home/deignis-prod/webapps/deignis-web-production/releases/1670155807541/vendor/ynmstudio/craft-utils/src/services/Seo.php(155): ynmstudio\\craftutils\\services\\Content->extractText()","#2 /home/deignis-prod/webapps/deignis-web-production/releases/1670155807541/vendor/twig/twig/src/Extension/CoreExtension.php(1607): ynmstudio\\craftutils\\services\\Seo->seoKeywords()","#3 /home/deignis-prod/webapps/deignis-web-production/releases/1670155807541/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute()","#4 /home/deignis-prod/webapps/deignis-web-production/storage/runtime/compiled_templates/92/9216b48d3bc7fc7bf7fcaf6e5d3eaa68.php(38): craft\\helpers\\Template::attribute()","#5 /home/deignis-prod/webapps/deignis-web-production/releases/1670155807541/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b4e99fd3629e45b668925e51dc18665d->doDisplay()","#6```

https://github.com/yoannisj/craft-tailor/blob/9c71118a2959bfe8357512ccf6ebf81f03976d26/src/helpers/ContentHelper.php#L420

**Comment by denisyilmaz** [comment]
this is kind of important because it results in the frontend being broken for initial, uncached requests. probably because after initial call to a url the html is cached (wich errored seo fields) and therefore not resolved again via seomatic

**Comment by yoannisj** [comment]
@denisyilmaz could you point me in the right direction to re-produce this error? Thanks!
